# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.0
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.396
  hooks:
  - id: pyright
- repo: https://github.com/sbdchd/squawk
  rev: v1.6.0
  hooks:
    - id: squawk
      files: src/registration_app/db/migrations/
    - id: squawk
      files: src/regular_export/queries/
